version: "2"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - "8000:3000"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      # Permite sincronizar la carpeta de trabajo durante el desarrollo
      # de la aplicación
  db:
    image: mongo
    ports: 
      - "27017:27017"
    restart: always
    volumes: 
      - mongodb://localhost/TODOdb
    command: mongod --auth
volumes:
  mongodb: